import "./HowToSection.css";
const HowToSection = () => {
  return (
    <section className="how-to-section">
      <h2 className="section-title">How to Use Deepfake Voice Detection</h2>
      <p className="section-subtitle">
        It's fast and super simple. Just follow a few easy steps to check if your audio is real or fake.
        No tech skills needed—our AI handles the hard stuff. You'll get clear results you can download and share.
      </p>
      <div className="how-to-content">
        <div className="how-to-steps">
          <div className="step">
            <div className="step-header">
              <span className="step-icon">⬆️</span>
              <h3 className="step-title">Step 1: Upload Your Audio File</h3>
            </div>
            <p className="step-desc">
              Click the upload button to select a voice recording from your device. We support most formats like MP3, WAV, and M4A.
              Make sure the audio is clear and at least a few seconds long so the AI can analyze it properly.
            </p>
          </div>
          <div className="step">
            <div className="step-header">
              <span className="step-icon">🤖</span>
              <h3 className="step-title">Step 2: Detect Voice</h3>
            </div>
            <p className="step-desc">
              Once your file is uploaded, our AI instantly starts analyzing the audio. It checks pitch, pauses,
              background noise, and more. In about 10—30 seconds, we'll tell you how likely the voice is real or generated by AI.
            </p>
          </div>
          <div className="step">
            <div className="step-header">
              <span className="step-icon">📊</span>
              <h3 className="step-title">Step 3: Review the Detection Report</h3>
            </div>
            <p className="step-desc">
              You'll see a simple result: a score showing how real or fake the voice sounds. We also highlight suspicious
              time points so you know exactly where problems might be. You get both a quick summary and a full detailed report.
            </p>
          </div>
          <div className="step">
            <div className="step-header">
              <span className="step-icon">⬇️</span>
              <h3 className="step-title">Step 4: Download or Share Your Results</h3>
            </div>
            <p className="step-desc">
              Need to keep a record or show someone else? Just click to download the report as a file.
              You can also copy a shareable link if you want to send it to a colleague.
            </p>
          </div>
        </div>
        <div className="how-to-visual">
          <div className="visual-step">
            <div className="visual-number">1</div>
            <span className="visual-label">Upload</span>
          </div>
          <div className="visual-upload-box">
            <div className="upload-icon">☁️</div>
            <p>Drag & drop an audio file or click</p>
            <p>WAV, MP3, AAC, OGG, FLAC up to 20MB</p>
          </div>
          <div className="visual-step">
            <div className="visual-number">2</div>
            <span className="visual-label">Submit</span>
          </div>
          <div className="visual-submit-box">
            <div className="waveform">
              {[20, 28, 14, 32, 18, 26, 10].map((h, i) => (
                <div key={i} className="waveform-bar" style={{ height: `${h}px` }} />
              ))}
            </div>
            <button className="visual-analyze-btn">Analyze Audio</button>
          </div>
          <div className="visual-step">
            <div className="visual-number" style={{ background: "#3182ce" }}>3</div>
            <span className="visual-label">Get result</span>
          </div>
          <div className="visual-result-box">
            <div className="result-score">10<span>%</span></div>
            <p className="result-label">Potential Deepfake</p>
          </div>
        </div>
      </div>
    </section>
  );
};
export default HowToSection;
